services:
  everythingblk:
    container_name: everythingblk
    build: .
    image: everythingblk:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: everythingblkDB
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: strapi
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      - everythingblk
    depends_on:
      everythingblkDB:
        condition: service_healthy

  everythingblkDB:
    container_name: everythingblkDB
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - everythingblk-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - everythingblk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d strapi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  everythingblk-data:

networks:
  everythingblk:
    name: Everythingblk
    driver: bridge